format: 0.3.0
primaryJobName: ipfs_deploy
jobs:
  deploy:
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: fs/./build
      - name: ens_deploy
        package: ens
        uri: $$ipfs_deploy
        config:
          domainName: simplestorage.eth
          provider: http://localhost:8545
          ensRegistryAddress: "0x5b1869D9A4C187F2EAa108f3062412ecf0526b24"
